run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - structcheck
    - unconvert
    - unparam
    - unused
