run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exportloopref
    - fatcontext
    - goconst
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tparallel
    - typecheck
    - unconvert
    - usestdlibvars
    - unparam
    - unused
