version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - goconst
    - godot
    - govet
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  exclusions:
    presets:
      - comments
      - std-error-handling
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - [""] # AllowList
            - [""] # DenyList
            # Ignore revive linter complaining about the names of packages.
            - - skip-package-name-checks: true
                skip-package-name-collision-with-go-std: true
formatters:
  enable:
    - gofmt
    - goimports
